### ISSUE TITLE
Improvement: Show a popup / toast message when "unlinked files output.md" does not exist upon deletion command

### ISSUE THREAD

**Issue by jorgb** [Vinzent03/find-unlinked-files#12]
When the file "unlinked files output.md" is not present, and I run the "delete files with certain extension" command, it 'fails' silently if the step "Find unlinked files" is not ran. It might be more informative to show a notification to the user that the first step needs to be ran first (it costed me a while to realise that was what was preventing attachments from being deleted).

**Comment by Vinzent03** [comment]
Sorry for the inconvenience. Will add that for sure.

**Comment by jorgb** [comment]
No problem, thank you for making the plugin!

**Comment by jorgb** [comment]
Thank you for your quick fix!
