### ISSUE TITLE
Plugin misses some types of linked files

### ISSUE THREAD

**Issue by BryanWall** [Vinzent03/find-unlinked-files#13]
I tested the plugin as a solution to finding orphaned attachments after seeing a forum post that you replied to suggesting it. I noticed that it identified a lot of files in my attachments folder that were not orphaned, but are using "alternate" link methods. Here's a forum thread referencing a couple of the other link-to-external-file methods supported by Obsidian:

[https://forum.obsidian.md/t/how-to-hide-attachment-folders-from-the-file-explorer-pane/18581/2](https://forum.obsidian.md/t/how-to-hide-attachment-folders-from-the-file-explorer-pane/18581/2)

One of them is this format, which AFAIK is the only way to get images to work in HTML inside Obsidian:
`<img src="app://local/Users/cusername/Documents/obsidian_notebook/some_folder/subfolder/test.jpg">`

The other is this, which is a way to embed images using a path. 
`![sunrise](file:///users/..../sunrise.png)`

Either of these methods can point to files inside the Obsidian folder. In my example I have them pointing to files inside the "attachments" folder. Is it possible for the plugin to identify if any of the files found are actually linked to by these methods, to eliminate false positives?

**Comment by Vinzent03** [comment]
My source of all links are the same that Obsidian handles to support for example backlinks. Markdown links like `![name](myFile.md)` are supported too. I don't know a way to correctly parse these links, so I won't be able to fix this. I suggest using Obsidian's linking feature, but I still understand your wish to hide the attachments' folder.
