### ISSUE TITLE
[issue] Unable to locate tags in Front Matter (Metadata)

### ISSUE THREAD

**Issue by HueLiu** [Vinzent03/find-unlinked-files#16]
Hi,

Now if Front Matters contains tags in the files, these files will also be treated as untagged files.

![image](https://user-images.githubusercontent.com/19755727/135557867-5f8b4a95-672f-4af2-84cb-b7bb8ec8d146.png)

Thank you.

**Comment by Vinzent03** [comment]
Sorry, should be fixed in [1.3.1](https://github.com/Vinzent03/find-unlinked-files/releases/tag/1.3.1)
