### ISSUE TITLE
Quick code review

### ISSUE THREAD

**Issue by lishid** [Vinzent03/find-unlinked-files#2]
https://github.com/Vinzent03/find-unlinked-files/blob/9c4ee4820a1a09b78d7e0610c238810d9d804327/main.ts#L8

`loadData` is only a JSON parse, which returns a simple object with no prototype. This should still work since you don't rely on the class "Settings" really, but I recommend you use an interface instead of a class.

https://github.com/Vinzent03/find-unlinked-files/blob/9c4ee4820a1a09b78d7e0610c238810d9d804327/main.ts#L17

You can use `let variable: Type[] = [];` instead of initializing it on next line.

https://github.com/Vinzent03/find-unlinked-files/blob/9c4ee4820a1a09b78d7e0610c238810d9d804327/main.ts#L23

Recommend you use [iterateCacheRefs](https://github.com/obsidianmd/obsidian-api/blob/master/obsidian.d.ts#L881) instead, which takes care of all your edge cases for you.

https://github.com/Vinzent03/find-unlinked-files/blob/9c4ee4820a1a09b78d7e0610c238810d9d804327/main.ts#L53

Recommend you change the whole function to an `async` function and use `await` here instead of `.then()`.

**Comment by Vinzent03** [comment]
Thank you for your tips.
I was searching for the syntax, but I don't know why I didn't come up with `let variable: Type[] = [];`
