### ISSUE TITLE
Don't include sibling files that have a filename starting with the directory name

### ISSUE THREAD

**Issue by Vuenc** [Vinzent03/find-unlinked-files#24]
I have a directory called "References" and an (unlinked) file called "References.md" on the same level as the directory. When I execute "find unlinked files" on the directory, the output includes "References.md" despite the file not being under the directoy.

The same problem occurs when the directory is e.g. just called "Ref". Also if I have a directory called "Ref" and a sibling directory called "References", searching for unlinked files in "Ref" also includes unlinked files in "References".

**Comment by Vinzent03** [comment]
Should be fixed in the new version.

**Comment by Vuenc** [comment]
Thanks a lot :)
