### ISSUE TITLE
Great plugin but hard/impossible to see what has changed in the releases section

### ISSUE THREAD

**Issue by aubreyz** [Vinzent03/find-unlinked-files#25]
As the header says. I think this is an "issue"

**Comment by huyz** [comment]
There used to be a plugin that let me quickly see what has changed (or what will change when I hit the "Update" button) https://github.com/phibr0/obsidian-plugin-changelogs
but it just has been archived with no explanation.

Actually, looking at the changelog history of this `find-unliked-files` plugin, there isn't much commentary so the plugin wouldn't have been useful anyway.

**Comment by aubreyz** [comment]
Surely it just needs a one or two line summary with each release stating what the major changes are.

**Comment by Vinzent03** [comment]
There is now a CHANGELOG file in the root directory.
