### ISSUE TITLE
About auto open notes

### ISSUE THREAD

**Issue by chenxuan353** [Vinzent03/find-unlinked-files#27]
Is it possible to add the ability to turn off the automatic opening of notes?

**Comment by Vinzent03** [comment]
You mean the output file, where all unlinked files are listed?

**Comment by chenxuan353** [comment]
Is an automatic opening after running the command

**Comment by Vinzent03** [comment]
Sorry, but I don't see the use case. Why don't you want the file to be opened?

**Comment by chenxuan353** [comment]
I want to automate using the buttons plugin, but running the relevant command opens the file window.
Also, multiple executions will open multiple windows.

**Comment by Vinzent03** [comment]
That's an interesting use case. Available in new release!

**Comment by chenxuan353** [comment]
thanks!
