### ISSUE TITLE
Unique name for output file

### ISSUE THREAD

**Issue by ryjjin** [Vinzent03/find-unlinked-files#3]
Great plugin, thanks!

It's not critical, but can you add the option for setting the name of output file? 
This can be useful for users like me who have a lot of notes in the root folder and who constantly forget what the output file is called :)

**Comment by Vinzent03** [comment]
You can just recall the command. The output file will be opened automatically. With the newest release even in an new pane. But if you want to I can add this option too.

**Comment by ryjjin** [comment]
> The output file will be opened automatically

Hmm, in my case it works on a mac, but does not work on win - the output file was only created there, not opened

**Comment by Vinzent03** [comment]
Hmm, if you open the console and call the command on win, is there any error? Which version is it?

**Comment by ryjjin** [comment]
I reloaded Obsidian via ctrl+R, and now it's opening :)
Now I happy and don't want anymore else 😊

Thanks!

**Comment by Vinzent03** [comment]
Great to hear. I dont know why it didn't work, but if it works after reload I think everything is fine.
