### ISSUE TITLE
i wanner include directory not exclude 

### ISSUE THREAD

**Issue by FBIshouxi** [Vinzent03/find-unlinked-files#31]
it's the opposite to me, i make a directory named file to store all the resource file, i want to delete files who not used in this directory

**Comment by Vinzent03** [comment]
There should be a toggle before the text field.

**Comment by FBIshouxi** [comment]
sorry, i find it just now, thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月21日(星期天) 下午5:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Vinzent03/find-unlinked-files] i wanner include directory not exclude  (Issue #31)





 
There should be a toggle before the text field.
