### ISSUE TITLE
选择删除附件，会删除掉一些不想删除的文件

### ISSUE THREAD

**Issue by zuojinxin** [Vinzent03/find-unlinked-files#39]
能否指定哪些类型文件或是哪些文件不被删除，因为有一些插件附件需要放置在根目录下

**Comment by zuojinxin** [comment]
好吧，商店下载的版本才1.1，好多功能没有

**Comment by Vinzent03** [comment]
Please describe your issue in English. You have to list the file types to delete in the settings. This should prevent you from deleting unwanted file types.generalpy on invoking the delete files command. Only the files already listed in the output note get deleted.
