### ISSUE TITLE
Plugin Request: Make the repo name (or the name that appears in the plugin store) the same as the name in manifest.json

### ISSUE THREAD

**Issue by Oneechan69** [Vinzent03/find-unlinked-files#42]
Right now, the plugin is called "find unlinked files" in the plugin store. However, when I install it, its called "Find orphaned files and broken links." I had installed the plugin awhile ago, when I did I was wondering where the plugin was since it didn't show up after writing "find unlinked files" in the search bar. I recently looked at all the repos your profile page. I thought this was a different plugin.

**Comment by Vinzent03** [comment]
Thanks for the hint. Done!
