### ISSUE TITLE
Customizable output file name

### ISSUE THREAD

**Issue by inputsh** [Vinzent03/find-unlinked-files#5]
Hi, thanks for the plugin!

Can we get customizable file name for the output? Currently I don't see it configurable in the settings for this plugin, and I'd like to use something else than `Find unlinked files plugin output`.

**Comment by Vinzent03** [comment]
As I said in #3 I thought it would not be necessary, because you can just recall the command. But if the wish comes twice, I can add this of course. When I choose the file name, it was important that no other file exists with this name,  because it would outherwise be overwritten.

**Comment by inputsh** [comment]
You can add a warning to choose a file that's not populated with something else in the description of the setting. I've tried renaming the file and re-triggering the file, but, as expected `Find unlinked files plugin output` gets re-created.

Some examples as to why:

* Some people might prefer not to have spaces in note names, replacing them with some sort of a dash.
* Some people might want to prepend something to the file name (like an emoji).
* Some people might prefer shorter titles for notes.

In any of those examples, the output file of this plugin will stick out from the rest of their vault, which is definitely not a reason not to use the plugin, just a slight annoyance.

In my specific case, other titles are short enough that there's no horizontal scroll in the file explorer, but when I trigger this plugin the name is long enough for it to appear. Since I'm primarily using a touchpad, if I swipe slightly to the right by accident while navigating the file explorer up/down, I can no longer see any of the other note/folder names:

![Screenshot from 2020-12-27 12 46 46](https://user-images.githubusercontent.com/4890548/103170057-9da76700-4841-11eb-82d0-f5d0c168b979.png)


This annoyance would go away if I could change the output file name of this plugin.

**Comment by Vinzent03** [comment]
Ok thats a very good reason, I am already working on it.

**Comment by Vinzent03** [comment]
New [release](https://github.com/Vinzent03/find-unlinked-files/releases/tag/0.2.5) is out, I hope it workes perfect.
