### ISSUE TITLE
Find broken block references and invalid section

### ISSUE THREAD

**Issue by HelloHumans13** [Vinzent03/find-unlinked-files#50]
When I delete an internal link, the block identifiers isn't updated. Also I would like to find links with invalid section.

**Comment by Vinzent03** [comment]
Please describe more in detail what you want. Do you want links to non existing heading and/or blocks, or find block ids that are no longer linked to?

**Comment by HelloHumans13** [comment]
I want to find and delete links to non existing heading/blocks and block ids that are no longer linked.

**Comment by jvdevlab** [comment]
Seems to be a dupe of https://github.com/Vinzent03/find-unlinked-files/issues/36 (maybe upvote there)
