### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'end')

### ISSUE THREAD

**Issue by annekaelber** [Vinzent03/find-unlinked-files#51]
Hello,

I'm running:
Win 10 Home
Obsidian 1.4.2
Find orphaned files and broken links 1.9.0

The attached image is the error I see in the console. (If you came here from a search: Win Ctrl-Shift-I opens the console. That's a capital i, too.)

Here's the text of the error, so others can find this ( but the image is much more legible):

plugin:find-unlinked-files:838 
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'end')
    at FindOrphanedFilesPlugin.eval (plugin:find-unlinked-files:838:54)
    at step (plugin:find-unlinked-files:68:23)
    at Object.eval [as next] (plugin:find-unlinked-files:49:53)
    at fulfilled (plugin:find-unlinked-files:39:58)
		eval	@	plugin:find-unlinked-files:838
step	@	plugin:find-unlinked-files:68
eval	@	plugin:find-unlinked-files:49
fulfilled	@	plugin:find-unlinked-files:39
Promise.then (async)		
step	@	plugin:find-unlinked-files:41
fulfilled	@	plugin:find-unlinked-files:39
Promise.then (async)		
step	@	plugin:find-unlinked-files:41
eval	@	plugin:find-unlinked-files:42
__awaiter	@	plugin:find-unlinked-files:38
FindOrphanedFilesPlugin.findEmptyFiles	@	plugin:find-unlinked-files:812
callback	@	plugin:find-unlinked-files:735
kW	@	app.js:1
t.onChooseItem	@	app.js:1
t.onChooseSuggestion	@	app.js:1
t.selectSuggestion	@	app.js:1
e.useSelectedItem	@	app.js:1
e.onSuggestionClick	@	app.js:1
s	@	enhance.js:1

No file gets created, but I still have "broken links output" and "files without tags" and "orphaned files output" from  a previous run. I copied the files outside my vault and deleted them from the vault, then ran "find orphaned files". The result is 2600 files that are orphans. I ran "find emptied files" again and got the same error.

Thanks,
Anne

![find-uncaught-error](https://github.com/Vinzent03/find-unlinked-files/assets/15622000/2f4160e2-b2ba-4d8d-af74-8bb8ea21e1d5)

**Comment by luckman212** [comment]
Came to report the same error...

- Obsidian 1.4.3 (Installer 1.3.7)
- macOS 13.5.1
- Plugin ver 1.9.0

![image](https://github.com/Vinzent03/find-unlinked-files/assets/1992842/0c20069e-80da-4f88-9778-7d3a10cc044e)

![image](https://github.com/Vinzent03/find-unlinked-files/assets/1992842/da65ddca-fc54-4a41-bdad-ec36c450126a)

**Comment by Vinzent03** [comment]
I see now that's a breaking change in the api that was not mentioned in the release notes in the Discord so I didn't know. It's listed [here](https://obsidian.md/changelog/2023-07-26-desktop-v1.4.0/). Fixing now...
