### ISSUE TITLE
Add functionality: Show notes with no backlinks OR links out

### ISSUE THREAD

**Issue by SquidLord** [Vinzent03/find-unlinked-files#7]
For my personal use case, it would be extremely handy to be able to find notes which don't link outwards and don't have any inbound links. I often use notes which only have back links as _nexus nodes_, and as configured they just get thrown into this huge list despite being quite useful.

Any chance that we can see the ability to refine it a little further in the future?

**Comment by Vinzent03** [comment]
So want an extra option to only find files which have neither backlinks nor links to other files?

**Comment by Vinzent03** [comment]
I think your title and your description mean not the same.
