### ISSUE TITLE
Find "unfiled" link feature?

### ISSUE THREAD

**Issue by lkhphuc** [Vinzent03/find-unlinked-files#8]
I wonder if it's possible (or in the scope of this plugin) to have that feature, which is to find all the links I have created everywhere else but a file has not yet been created.
Obsidian support auto-completion to all the links regardless if a file has been created or not, so if I know I want something, I can link to it again. 

But sometime I just want to browser all the links, which I can do through the file explorer or tags pane, both require that file for that link to have been created before.

**Comment by Vinzent03** [comment]
You want to find links, where the file of the link has not been created yet?

**Comment by lkhphuc** [comment]
Yes, basically.
